// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheContentor.Infrastructure;

#nullable disable

namespace TheContentor.Infrastructure.Migrations
{
    [DbContext(typeof(TheContentorDbContext))]
    [Migration("20260220185504_AddProcessedPostIsPosted")]
    partial class AddProcessedPostIsPosted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheContentor.Domain.Entities.AnalysisCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Engine")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalysisCriteria");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ContentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiReasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("AttractivenessScore")
                        .HasColumnType("real");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("SourcePostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("SourcePostId");

                    b.ToTable("ContentAnalyses");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.PostMetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourcePostId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UpvoteRatio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SourcePostId", "CapturedUtc")
                        .IsUnique();

                    b.ToTable("PostMetricSnapshots", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ProcessedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsPosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("NarratorGender")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TtsSettings")
                        .HasColumnType("text");

                    b.Property<int>("TtsStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VideoSettings")
                        .HasColumnType("text");

                    b.Property<int>("VideoStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProcessedPosts", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ProcessedPostPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("AudioDuration")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<List<string>>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Part")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessedPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("PublishedTo")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedPostId", "Part")
                        .IsUnique();

                    b.ToTable("ProcessedPostParts", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.RedditPostData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AuthorCommentKarma")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AuthorCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AuthorLinkKarma")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FlairText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAuthorDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelfPost")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStickied")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Subreddit")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("TotalAwardsReceived")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("Subreddit");

                    b.ToTable("RedditPostData", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.SourceComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("ParentExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourcePostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("SourcePostId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("SourcePostId", "Score");

                    b.ToTable("SourceComments", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.SourcePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CommunityExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Flairs")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("IngestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastRefreshedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RawHtml")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("UpvoteRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("IngestedUtc");

                    b.HasIndex("Status");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique();

                    b.HasIndex("Platform", "Community", "CreatedUtc");

                    b.HasIndex("Platform", "Community", "Score", "CreatedUtc");

                    b.ToTable("SourcePosts", (string)null);
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.VideoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorLog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinalVideoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GeneratedAudioPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SourcePostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubStyle")
                        .HasColumnType("integer");

                    b.Property<int>("SubtitleEngine")
                        .HasColumnType("integer");

                    b.Property<string>("SubtitleFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TtsEngine")
                        .HasColumnType("integer");

                    b.Property<string>("VoiceProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("SourcePostId");

                    b.ToTable("VideoProjects");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.Asset", b =>
                {
                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "BlobPath", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("BlobPath")
                        .IsRequired();
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ContentAnalysis", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.AnalysisCriteria", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithMany()
                        .HasForeignKey("SourcePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.PostMetricSnapshot", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithMany("MetricSnapshots")
                        .HasForeignKey("SourcePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ProcessedPost", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithOne("ProcessedPost")
                        .HasForeignKey("TheContentor.Domain.Entities.ProcessedPost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "DescriptionAudioBlobPath", b1 =>
                        {
                            b1.Property<Guid>("ProcessedPostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DescriptionAudioPath");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DescriptionAudioContainer");

                            b1.HasKey("ProcessedPostId");

                            b1.ToTable("ProcessedPosts");

                            b1.WithOwner()
                                .HasForeignKey("ProcessedPostId");
                        });

                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "VideoBlobPath", b1 =>
                        {
                            b1.Property<Guid>("ProcessedPostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VideoPath");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VideoContainer");

                            b1.HasKey("ProcessedPostId");

                            b1.ToTable("ProcessedPosts");

                            b1.WithOwner()
                                .HasForeignKey("ProcessedPostId");
                        });

                    b.Navigation("DescriptionAudioBlobPath");

                    b.Navigation("SourcePost");

                    b.Navigation("VideoBlobPath");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ProcessedPostPart", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.ProcessedPost", "ProcessedPost")
                        .WithMany("Parts")
                        .HasForeignKey("ProcessedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "AudioBlobPath", b1 =>
                        {
                            b1.Property<Guid>("ProcessedPostPartId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AudioPath");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AudioContainer");

                            b1.HasKey("ProcessedPostPartId");

                            b1.ToTable("ProcessedPostParts");

                            b1.WithOwner()
                                .HasForeignKey("ProcessedPostPartId");
                        });

                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "SubtitleBlobPath", b1 =>
                        {
                            b1.Property<Guid>("ProcessedPostPartId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SubtitlePath");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SubtitleContainer");

                            b1.HasKey("ProcessedPostPartId");

                            b1.ToTable("ProcessedPostParts");

                            b1.WithOwner()
                                .HasForeignKey("ProcessedPostPartId");
                        });

                    b.OwnsOne("TheContentor.Domain.Entities.BlobPath", "VideoBlobPath", b1 =>
                        {
                            b1.Property<Guid>("ProcessedPostPartId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssetPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VideoPath");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("VideoContainer");

                            b1.HasKey("ProcessedPostPartId");

                            b1.ToTable("ProcessedPostParts");

                            b1.WithOwner()
                                .HasForeignKey("ProcessedPostPartId");
                        });

                    b.Navigation("AudioBlobPath");

                    b.Navigation("ProcessedPost");

                    b.Navigation("SubtitleBlobPath");

                    b.Navigation("VideoBlobPath");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.RedditPostData", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithOne()
                        .HasForeignKey("TheContentor.Domain.Entities.RedditPostData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.SourceComment", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithMany("Comments")
                        .HasForeignKey("SourcePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.VideoProject", b =>
                {
                    b.HasOne("TheContentor.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheContentor.Domain.Entities.SourcePost", "SourcePost")
                        .WithMany()
                        .HasForeignKey("SourcePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.ProcessedPost", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("TheContentor.Domain.Entities.SourcePost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MetricSnapshots");

                    b.Navigation("ProcessedPost");
                });
#pragma warning restore 612, 618
        }
    }
}
